// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuickFlow.BE.Repositories;

#nullable disable

namespace QuickFlow.BE.Repositories.Migrations
{
    [DbContext(typeof(QuickFlowDbContext))]
    [Migration("20251201081232_Test1")]
    partial class Test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuickFlow.BE.Entities.MstUser", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_name");

                    b.HasKey("RowId")
                        .HasName("pk_mst_user");

                    b.HasIndex("LoginName")
                        .IsUnique()
                        .HasDatabaseName("ix_mst_user_login_name");

                    b.ToTable("mst_user", (string)null);

                    b.HasData(
                        new
                        {
                            RowId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "Administrator",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            LoginName = "admin"
                        });
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.MstWfStateType", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RowId")
                        .HasName("pk_mst_wf_state_type");

                    b.ToTable("mst_wf_state_type", (string)null);

                    b.HasData(
                        new
                        {
                            RowId = 1,
                            Name = "Start"
                        },
                        new
                        {
                            RowId = 2,
                            Name = "End"
                        },
                        new
                        {
                            RowId = 3,
                            Name = "Normal"
                        });
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstance", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CurrentWfStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_wf_state_id");

                    b.Property<string>("DocId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("WfTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("wf_template_id");

                    b.HasKey("RowId")
                        .HasName("pk_wf_instance");

                    b.HasIndex("CurrentWfStateId")
                        .HasDatabaseName("ix_wf_instance_current_wf_state_id");

                    b.HasIndex("DocId")
                        .IsUnique()
                        .HasDatabaseName("ix_wf_instance_doc_id");

                    b.HasIndex("WfTemplateId")
                        .HasDatabaseName("ix_wf_instance_wf_template_id");

                    b.ToTable("wf_instance", (string)null);
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstanceTask", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WfInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("wf_instance_id");

                    b.HasKey("RowId")
                        .HasName("pk_wf_instance_task");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_wf_instance_task_user_id");

                    b.HasIndex("WfInstanceId")
                        .HasDatabaseName("ix_wf_instance_task_wf_instance_id");

                    b.ToTable("wf_instance_task", (string)null);
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplate", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("RowId")
                        .HasName("pk_wf_template");

                    b.ToTable("wf_template", (string)null);

                    b.HasData(
                        new
                        {
                            RowId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "DummyTemplate",
                            Version = 1
                        });
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplateState", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("MstWfStateTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("mst_wf_state_type_id");

                    b.Property<Guid>("WfTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("wf_template_id");

                    b.HasKey("RowId")
                        .HasName("pk_wf_template_state");

                    b.HasIndex("MstWfStateTypeId")
                        .HasDatabaseName("ix_wf_template_state_mst_wf_state_type_id");

                    b.HasIndex("WfTemplateId")
                        .HasDatabaseName("ix_wf_template_state_wf_template_id");

                    b.ToTable("wf_template_state", (string)null);

                    b.HasData(
                        new
                        {
                            RowId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            MstWfStateTypeId = 1,
                            WfTemplateId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstance", b =>
                {
                    b.HasOne("QuickFlow.BE.Entities.WfTemplateState", "CurrentWfState")
                        .WithMany("WfInstances")
                        .HasForeignKey("CurrentWfStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instance_wf_template_state_current_wf_state_id");

                    b.HasOne("QuickFlow.BE.Entities.WfTemplate", "WfTemplate")
                        .WithMany("WfInstances")
                        .HasForeignKey("WfTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instance_wf_template_wf_template_id");

                    b.Navigation("CurrentWfState");

                    b.Navigation("WfTemplate");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstanceTask", b =>
                {
                    b.HasOne("QuickFlow.BE.Entities.MstUser", "User")
                        .WithMany("WfInstanceTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instance_task_mst_user_user_id");

                    b.HasOne("QuickFlow.BE.Entities.WfInstance", "WfInstance")
                        .WithMany("WfInstanceTasks")
                        .HasForeignKey("WfInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instance_task_wf_instance_wf_instance_id");

                    b.Navigation("User");

                    b.Navigation("WfInstance");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplateState", b =>
                {
                    b.HasOne("QuickFlow.BE.Entities.MstWfStateType", "MstWfStateType")
                        .WithMany("WfTemplateStates")
                        .HasForeignKey("MstWfStateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_template_state_mst_wf_state_type_mst_wf_state_type_id");

                    b.HasOne("QuickFlow.BE.Entities.WfTemplate", "WfTemplate")
                        .WithMany("WfTemplateStates")
                        .HasForeignKey("WfTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_template_state_wf_template_wf_template_id");

                    b.Navigation("MstWfStateType");

                    b.Navigation("WfTemplate");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.MstUser", b =>
                {
                    b.Navigation("WfInstanceTasks");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.MstWfStateType", b =>
                {
                    b.Navigation("WfTemplateStates");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstance", b =>
                {
                    b.Navigation("WfInstanceTasks");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplate", b =>
                {
                    b.Navigation("WfInstances");

                    b.Navigation("WfTemplateStates");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplateState", b =>
                {
                    b.Navigation("WfInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
