// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuickFlow.BE.Repositories;

#nullable disable

namespace QuickFlow.BE.Repositories.Migrations
{
    [DbContext(typeof(QuickFlowDbContext))]
    partial class QuickFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuickFlow.BE.Entities.MstUser", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_name");

                    b.HasKey("RowId")
                        .HasName("pk_mst_users");

                    b.HasIndex("LoginName")
                        .IsUnique()
                        .HasDatabaseName("ix_mst_users_login_name");

                    b.ToTable("mst_users", (string)null);

                    b.HasData(
                        new
                        {
                            RowId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "Administrator",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            LoginName = "admin"
                        });
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstance", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CurrentWfStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_wf_state_id");

                    b.Property<string>("DocId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("WfTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("wf_template_id");

                    b.HasKey("RowId")
                        .HasName("pk_wf_instances");

                    b.HasIndex("CurrentWfStateId")
                        .HasDatabaseName("ix_wf_instances_current_wf_state_id");

                    b.HasIndex("DocId")
                        .IsUnique()
                        .HasDatabaseName("ix_wf_instances_doc_id");

                    b.HasIndex("WfTemplateId")
                        .HasDatabaseName("ix_wf_instances_wf_template_id");

                    b.ToTable("wf_instances", (string)null);
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstanceTask", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WfInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("wf_instance_id");

                    b.HasKey("RowId")
                        .HasName("pk_wf_instance_tasks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_wf_instance_tasks_user_id");

                    b.HasIndex("WfInstanceId")
                        .HasDatabaseName("ix_wf_instance_tasks_wf_instance_id");

                    b.ToTable("wf_instance_tasks", (string)null);
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplate", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("RowId")
                        .HasName("pk_wf_templates");

                    b.ToTable("wf_templates", (string)null);
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplateState", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("WfTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("wf_template_id");

                    b.HasKey("RowId")
                        .HasName("pk_wf_template_states");

                    b.HasIndex("WfTemplateId")
                        .HasDatabaseName("ix_wf_template_states_wf_template_id");

                    b.ToTable("wf_template_states", (string)null);
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstance", b =>
                {
                    b.HasOne("QuickFlow.BE.Entities.WfTemplateState", "CurrentWfState")
                        .WithMany("WfInstances")
                        .HasForeignKey("CurrentWfStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instances_wf_template_states_current_wf_state_id");

                    b.HasOne("QuickFlow.BE.Entities.WfTemplate", "WfTemplate")
                        .WithMany("WfInstances")
                        .HasForeignKey("WfTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instances_wf_templates_wf_template_id");

                    b.Navigation("CurrentWfState");

                    b.Navigation("WfTemplate");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstanceTask", b =>
                {
                    b.HasOne("QuickFlow.BE.Entities.MstUser", "User")
                        .WithMany("WfInstanceTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instance_tasks_mst_users_user_id");

                    b.HasOne("QuickFlow.BE.Entities.WfInstance", "WfInstance")
                        .WithMany("WfInstanceTasks")
                        .HasForeignKey("WfInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_instance_tasks_wf_instances_wf_instance_id");

                    b.Navigation("User");

                    b.Navigation("WfInstance");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplateState", b =>
                {
                    b.HasOne("QuickFlow.BE.Entities.WfTemplate", "WfTemplate")
                        .WithMany("WfTemplateStates")
                        .HasForeignKey("WfTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wf_template_states_wf_templates_wf_template_id");

                    b.Navigation("WfTemplate");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.MstUser", b =>
                {
                    b.Navigation("WfInstanceTasks");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfInstance", b =>
                {
                    b.Navigation("WfInstanceTasks");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplate", b =>
                {
                    b.Navigation("WfInstances");

                    b.Navigation("WfTemplateStates");
                });

            modelBuilder.Entity("QuickFlow.BE.Entities.WfTemplateState", b =>
                {
                    b.Navigation("WfInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
